image: ubuntu:24.04

stages:
  - plan
  - apply

variables:
  TOFU_VERSION: "1.9.1"
  TF_IN_AUTOMATION: "true"
  TF_INPUT: "false"
  TF_USERNAME: "gitlab-ci-token"
  TF_ADDRESS: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/homelab-k8s"
  N8N_WEBHOOK_URL: "${N8N_WEBHOOK_URL}"

before_script:
  - apt-get update && apt-get install -y curl unzip
  - curl -sLo tofu.zip https://github.com/opentofu/opentofu/releases/download/v${TOFU_VERSION}/tofu_${TOFU_VERSION}_linux_amd64.zip
  - unzip -o -q tofu.zip
  - mv tofu /usr/local/bin/
  - chmod +x /usr/local/bin/tofu
  - tofu --version

.configure_backend: &configure_backend
  - tofu init -backend-config=address=${TF_ADDRESS} -backend-config=lock_address=${TF_ADDRESS}/lock -backend-config=unlock_address=${TF_ADDRESS}/lock -backend-config=username=${TF_USERNAME} -backend-config=password=${CI_JOB_TOKEN} -backend-config=lock_method=POST -backend-config=unlock_method=DELETE -backend-config=retry_wait_min=5

plan:
  stage: plan
  script:
    - *configure_backend
    - tofu plan -out=planfile
    - |
        tofu show -json planfile | curl -X POST -H "Content-Type: application/json" -d @- $N8N_WEBHOOK_URL"
  only:
    - main

apply:
  stage: apply
  script:
    - *configure_backend
    - tofu apply -auto-approve
  dependencies:
    - plan
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && $TRIGGER_APPLY == "true"'
      when: always
    - when: never
