spec:
  inputs:
    # Stages
    stage_validate:
      default: 'validate'
      description: 'Defines the validate stage. This stage includes the `fmt` and `validate` jobs.'
    stage_build:
      default: 'build'
      description: 'Defines the build stage. This stage includes the `plan` job.'
    stage_deploy:
      default: 'deploy'
      description: 'Defines the deploy stage. This stage includes the `apply` job.'

    # Versions
    # This version is only required, because we cannot access the context of the component,
    # see https://gitlab.com/gitlab-org/gitlab/-/issues/438275
    version:
      default: '2.6.1'
      description: 'Version of this component. Has to be the same as the one in the component include entry.'

    base_os:
      default: 'alpine'
      options:
        - 'alpine'
        - 'debian'
        - '$GITLAB_OPENTOFU_BASE_IMAGE_OS'
      description: 'Base OS of GitLab OpenTofu image.'

    opentofu_version:
      default: '1.9.1'
      options:
        - '1.9.1'
        - '1.9.0'
        - '1.8.9'
        - '1.8.8'
        - '1.7.8'
        - '1.7.7'
        - '1.6.3'
        - '$OPENTOFU_VERSION'
      description: 'OpenTofu version that should be used.'

    # Images
    image_registry_base:
      default: '$CI_TEMPLATE_REGISTRY_HOST/components/opentofu'
      description: 'Host URI to the job images. Will be combined with `image_name` to construct the actual image URI.'
    # FIXME: not yet possible because of https://gitlab.com/gitlab-org/gitlab/-/issues/438722
    # gitlab_opentofu_image:
    #   # FIXME: This should reference the component tag that is used.
    #   #        Currently, blocked by https://gitlab.com/gitlab-org/gitlab/-/issues/438275
    #   # default: '$CI_TEMPLATE_REGISTRY_HOST/components/opentofu/gitlab-opentofu:$[[ inputs.opentofu_version ]]'
    #   default: '$CI_TEMPLATE_REGISTRY_HOST/components/opentofu/gitlab-opentofu:$[[ inputs.version ]]-opentofu$[[ inputs.opentofu_version ]]'
    #   description: 'Tag of the gitlab-opentofu image.'

    image_name:
      default: 'gitlab-opentofu'
      description: 'Image name for the job images. Hosted under `image_registry_base`.'

    image_digest:
      default: ''
      # FIXME: we cannot use regex yet because of a bug that rejects
      # empty strings from ever being checked against the regex.
      # see https://gitlab.com/gitlab-org/gitlab/-/issues/477707
      # regex: '^(@sha256:[a-z0-9]{64})?$'
      description: 'Image digest of the image you want to use. The format must be `@<image_digest>`, e.g. `@sha256:abc..`, see regex of this input. Please consult the release page at https://gitlab.com/components/opentofu/-/releases to obtain the image digests.'

    # Configuration
    job_name_prefix:
      default: ''
      description: 'Prefix for all job names. Jobs will be hidden if leading with a dot `.`.'
    root_dir:
      default: ${CI_PROJECT_DIR}
      description: 'Root directory for the OpenTofu project.'
    state_name:
      default: default
      description: 'Remote OpenTofu state name.'
    plan_name:
      default: 'plan'
      description: 'The name of the plan cache and plan json file.'
    # FIXME: at the moment we cannot support this input
    # because we cannot nest inputs: https://gitlab.com/gitlab-org/gitlab/-/issues/438722
    # If you want to auto apply, please refer to the `rules` input.
    #auto_apply:
    #  default: false
    #  type: boolean
    #  description: 'Whether the apply job is manual or automatically run.'
    plan_artifacts_access:
      default: 'none'
      description: 'Access level for the plan artifact. See https://docs.gitlab.com/ee/ci/yaml/#artifactsaccess for possible values.'
    plan_extra_artifacts:
      default: []
      type: array
      description: 'Extra artifacts to upload from the plan'
    var_file:
      default: ''
      type: string
      description: 'Path to a variables files relative to root_dir.'
    fmt_allow_failure:
      default: true
      type: boolean
      description: 'Whether the fmt job is allowed to fail or not.'
    fmt_rules:
      default:
        - if: $CI_PIPELINE_SOURCE == "merge_request_event"
        # FIXME: once https://gitlab.com/gitlab-org/gitlab/-/issues/438722 is fixed we should only
        # match "parent_pipeline" source if $[[ inputs.trigger_in_child_pipeline ]] is `true`.
        - if: $CI_PIPELINE_SOURCE == "parent_pipeline"
        - if: $CI_OPEN_MERGE_REQUESTS  # Don't add it to a *branch* pipeline if it's already in a merge request pipeline.
          when: never
        - if: $CI_COMMIT_BRANCH        # If there's no open merge request, add it to a *branch* pipeline instead.
      type: array
      description: 'Defines the `rules` of the `fmt` job.'
    validate_rules:
      default:
        - if: $CI_PIPELINE_SOURCE == "merge_request_event"
        # FIXME: once https://gitlab.com/gitlab-org/gitlab/-/issues/438722 is fixed we should only
        # match "parent_pipeline" source if $[[ inputs.trigger_in_child_pipeline ]] is `true`.
        - if: $CI_PIPELINE_SOURCE == "parent_pipeline"
        - if: $CI_OPEN_MERGE_REQUESTS  # Don't add it to a *branch* pipeline if it's already in a merge request pipeline.
          when: never
        - if: $CI_COMMIT_BRANCH        # If there's no open merge request, add it to a *branch* pipeline instead.
      type: array
      description: 'Defines the `rules` of the `validate` job.'
    plan_rules:
      default:
        - if: $CI_PIPELINE_SOURCE == "merge_request_event"
        # FIXME: once https://gitlab.com/gitlab-org/gitlab/-/issues/438722 is fixed we should only
        # match "parent_pipeline" source if $[[ inputs.trigger_in_child_pipeline ]] is `true`.
        - if: $CI_PIPELINE_SOURCE == "parent_pipeline"
        - if: $CI_OPEN_MERGE_REQUESTS  # Don't add it to a *branch* pipeline if it's already in a merge request pipeline.
          when: never
        - if: $CI_COMMIT_BRANCH        # If there's no open merge request, add it to a *branch* pipeline instead.
      type: array
      description: 'Defines the `rules` of the `plan` job.'
    apply_rules:
      default:
        - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
          when: manual
      type: array
      description: 'Defines the `rules` of the `apply` job.'
    warning_on_non_empty_plan:
      default: false
      type: boolean
      description: 'Whether to mark the job with a warning if the plan contains a diff.'
    trigger_in_child_pipeline:
      default: false
      type: boolean
      description: 'Whether to run all the jobs in a child pipeline.'
    child_pipeline_name:
      default: opentofu
      type: string
      description: 'If `trigger_in_child_pipeline` is `true` then this defines the name of the child pipeline bridge job.'
    child_pipeline_stage:
      default: opentofu
      type: string
      description: 'If `trigger_in_child_pipeline` is `true` then this defines the stage of the child pipeline bridge job.'
    child_pipeline_rules:
      default: [{when: on_success}]
      type: array
      description: 'Defines the `rules` of the child pipeline bridge job.'
    auto_encryption:
      default: false
      type: boolean
      description: 'Whether to enable automatic state and plan encryption.'
    auto_encryption_passphrase:
      default: ''
      type: string
      description: 'Defines the passphrase to auto encrypt the state and plan. Only used if `auto_encryption` is `true`.'
    auto_encryption_enable_migration_from_unencrypted:
      default: false
      type: boolean
      description: 'Whether to setup automatic state and plan encryption for currently unencrypted state. This is only temporarily useful when migrating from an unencrypted state.'
    allow_developer_role_to_plan:
      default: false
      type: boolean
      description: 'Users with the Developer role are not able to lock the state. Thus a regular `tofu plan` fails. When set to `true` a `-lock=false` is passed to plan.'
    auto_define_backend:
      default: false
      type: boolean
      description: 'Whether to automatically define the HTTP backend configuration block.'
    enable_id_tokens:
      default: false
      type: boolean
      description: |
       Whether to enable `id_tokens` support for the pipeline.
       This works by extending a hidden base job configuration with the `id_tokens` field.
       The job should only contain the `id_tokens` field, the rest may be overridden.
       The job name can be configured with `id_tokens_base_job_name` if necessary.
       If the script given in `id_tokens_setup_script` exists, it will be sourced so that setup actions can be performed,
       like assuming an IAM role of your cloud provider.
    id_tokens_base_job_name:
      default: '.gitlab-tofu:id_tokens'
      type: string
      description: 'Name of the hidden base job containing the `id_tokens` configuration to extend the jobs from. Make sure to only configure `id_tokens`, everything else might be overridden.'
    id_tokens_setup_script:
      default: '.gitlab/ci/setup-id-tokens.sh'
      type: string
      description: 'Path to a shell script that is sourced when `enable_id_tokens` is `true`.'
    use_mr_plan:
      default: false
      type: boolean
      description: 'Whether to use the plan from the merge request pipeline of the current commit.'
    drift_detection_mode:
      default: refresh-only-apply
      options:
        - none
        - refresh-only-apply
        - refresh-only-plan
      description: |
        Mode for drift detection of fetched plan.
        By default a `tofu apply -refresh-only` is executed to refresh the state which would make the
        fetched plan stale for a subsequent apply if it contains changes.
        The `refresh-only-plan` option would only detect the drift, but wouldn't apply it, but it
        would let this job fail on drift.
        When using `none` no drift detection is performed at all.
    post_mr_plan_comment:
      default: false
      type: boolean
      description: 'Whether to post a comment in the Merge Request with the produced plan.'

---

include:
  - local: 'fmt.yml'
    rules:
      - if: '"$[[ inputs.trigger_in_child_pipeline ]]" == "false"'
    inputs:
      as: '$[[ inputs.job_name_prefix ]]fmt'
      stage: $[[ inputs.stage_validate ]]
      version: $[[ inputs.version ]]
      base_os: $[[ inputs.base_os ]]
      opentofu_version: $[[ inputs.opentofu_version ]]
      image_registry_base: $[[ inputs.image_registry_base ]]
      image_name: $[[ inputs.image_name ]]
      image_digest: $[[ inputs.image_digest ]]
      root_dir: $[[ inputs.root_dir ]]
      needs: []
      allow_failure: $[[ inputs.fmt_allow_failure ]]
      rules: $[[ inputs.fmt_rules ]]
  - local: '/templates/validate.yml'
    rules:
      - if: '"$[[ inputs.trigger_in_child_pipeline ]]" == "false"'
    inputs:
      as: '$[[ inputs.job_name_prefix ]]validate'
      stage: $[[ inputs.stage_validate ]]
      version: $[[ inputs.version ]]
      base_os: $[[ inputs.base_os ]]
      opentofu_version: $[[ inputs.opentofu_version ]]
      image_registry_base: $[[ inputs.image_registry_base ]]
      image_name: $[[ inputs.image_name ]]
      image_digest: $[[ inputs.image_digest ]]
      root_dir: $[[ inputs.root_dir ]]
      state_name: $[[ inputs.state_name ]]
      var_file: $[[ inputs.var_file ]]
      rules: $[[ inputs.validate_rules ]]
      cache_policy: pull-push
      auto_encryption: $[[ inputs.auto_encryption ]]
      auto_encryption_passphrase: $[[ inputs.auto_encryption_passphrase ]]
      auto_encryption_enable_migration_from_unencrypted: $[[ inputs.auto_encryption_enable_migration_from_unencrypted ]]
      auto_define_backend: $[[ inputs.auto_define_backend ]]
      enable_id_tokens: $[[ inputs.enable_id_tokens ]]
      id_tokens_base_job_name: $[[ inputs.id_tokens_base_job_name ]]
      id_tokens_setup_script: $[[ inputs.id_tokens_setup_script ]]
  - local: '/templates/plan.yml'
    rules:
      - if: '"$[[ inputs.use_mr_plan ]]" == "true"'
        when: never
      - if: '"$[[ inputs.trigger_in_child_pipeline ]]" == "false"'
    inputs:
      as: '$[[ inputs.job_name_prefix ]]plan'
      stage: $[[ inputs.stage_build ]]
      version: $[[ inputs.version ]]
      base_os: $[[ inputs.base_os ]]
      opentofu_version: $[[ inputs.opentofu_version ]]
      image_registry_base: $[[ inputs.image_registry_base ]]
      image_name: $[[ inputs.image_name ]]
      image_digest: $[[ inputs.image_digest ]]
      root_dir: $[[ inputs.root_dir ]]
      state_name: $[[ inputs.state_name ]]
      plan_name: $[[ inputs.plan_name ]]
      artifacts_access: $[[ inputs.plan_artifacts_access ]]
      extra_artifacts: $[[ inputs.plan_extra_artifacts ]]
      var_file: $[[ inputs.var_file ]]
      rules: $[[ inputs.plan_rules ]]
      cache_policy: pull
      warning_on_non_empty_plan: $[[ inputs.warning_on_non_empty_plan ]]
      auto_encryption: $[[ inputs.auto_encryption ]]
      auto_encryption_passphrase: $[[ inputs.auto_encryption_passphrase ]]
      auto_encryption_enable_migration_from_unencrypted: $[[ inputs.auto_encryption_enable_migration_from_unencrypted ]]
      allow_developer_role: $[[ inputs.allow_developer_role_to_plan ]]
      auto_define_backend: $[[ inputs.auto_define_backend ]]
      enable_id_tokens: $[[ inputs.enable_id_tokens ]]
      id_tokens_base_job_name: $[[ inputs.id_tokens_base_job_name ]]
      id_tokens_setup_script: $[[ inputs.id_tokens_setup_script ]]
      post_mr_plan_comment: $[[ inputs.post_mr_plan_comment ]]
  - local: '/templates/fetch-mr-plan.yml'
    rules:
      - if: '"$[[ inputs.use_mr_plan ]]" == "false"'
        when: never
      - if: '"$[[ inputs.trigger_in_child_pipeline ]]" == "false"'
    inputs:
      as: '$[[ inputs.job_name_prefix ]]fetch-mr-plan'
      stage: $[[ inputs.stage_build ]]
      version: $[[ inputs.version ]]
      base_os: $[[ inputs.base_os ]]
      opentofu_version: $[[ inputs.opentofu_version ]]
      image_registry_base: $[[ inputs.image_registry_base ]]
      image_name: $[[ inputs.image_name ]]
      image_digest: $[[ inputs.image_digest ]]
      root_dir: $[[ inputs.root_dir ]]
      state_name: $[[ inputs.state_name ]]
      plan_name: $[[ inputs.plan_name ]]
      artifacts_access: $[[ inputs.plan_artifacts_access ]]
      extra_artifacts: $[[ inputs.plan_extra_artifacts ]]
      var_file: $[[ inputs.var_file ]]
      rules: $[[ inputs.plan_rules ]]
      auto_encryption: $[[ inputs.auto_encryption ]]
      auto_encryption_passphrase: $[[ inputs.auto_encryption_passphrase ]]
      auto_encryption_enable_migration_from_unencrypted: $[[ inputs.auto_encryption_enable_migration_from_unencrypted ]]
      allow_developer_role: $[[ inputs.allow_developer_role_to_plan ]]
      auto_define_backend: $[[ inputs.auto_define_backend ]]
      drift_detection_mode: $[[ inputs.drift_detection_mode ]]
  - local: '/templates/apply.yml'
    rules:
      - if: '"$[[ inputs.trigger_in_child_pipeline ]]" == "false"'
    inputs:
      as: '$[[ inputs.job_name_prefix ]]apply'
      stage: $[[ inputs.stage_deploy ]]
      version: $[[ inputs.version ]]
      base_os: $[[ inputs.base_os ]]
      opentofu_version: $[[ inputs.opentofu_version ]]
      image_registry_base: $[[ inputs.image_registry_base ]]
      image_name: $[[ inputs.image_name ]]
      image_digest: $[[ inputs.image_digest ]]
      root_dir: $[[ inputs.root_dir ]]
      state_name: $[[ inputs.state_name ]]
      plan_name: $[[ inputs.plan_name ]]
      var_file: $[[ inputs.var_file ]]
      rules: $[[ inputs.apply_rules ]]
      cache_policy: pull
      auto_encryption: $[[ inputs.auto_encryption ]]
      auto_encryption_passphrase: $[[ inputs.auto_encryption_passphrase ]]
      auto_encryption_enable_migration_from_unencrypted: $[[ inputs.auto_encryption_enable_migration_from_unencrypted ]]
      auto_define_backend: $[[ inputs.auto_define_backend ]]
      enable_id_tokens: $[[ inputs.enable_id_tokens ]]
      id_tokens_base_job_name: $[[ inputs.id_tokens_base_job_name ]]
      id_tokens_setup_script: $[[ inputs.id_tokens_setup_script ]]


# NOTE: the following configuration is only used if `trigger_in_child_pipeline` is enabled.
stages:
  - $[[ inputs.stage_validate ]]
  - $[[ inputs.stage_build ]]
  - $[[ inputs.stage_deploy ]]
  - $[[ inputs.child_pipeline_stage ]]

'.$[[ inputs.job_name_prefix ]]$[[ inputs.child_pipeline_name ]]:bridge_job_stage:true':
  stage: $[[ inputs.child_pipeline_stage ]]

'.$[[ inputs.job_name_prefix ]]$[[ inputs.child_pipeline_name ]]:bridge_job_stage:false':
  # NOTE: this is a hack for the bridge job below to have a valid stage even if it isn't used.
  # The thing is that the stage needs to be defined even if the job is "ruled" out and not created.
  # The .pre stage always exists.
  stage: .pre

'$[[ inputs.job_name_prefix ]]$[[ inputs.child_pipeline_name ]]':
  rules:
    - if: '"$[[ inputs.trigger_in_child_pipeline ]]" == "false"'
      when: never
    - $[[ inputs.child_pipeline_rules ]]
  extends: '.$[[ inputs.job_name_prefix ]]$[[ inputs.child_pipeline_name ]]:bridge_job_stage:$[[ inputs.trigger_in_child_pipeline ]]'
  trigger:
    include:
      # FIXME: this project path may not be correct for forks and mirrors (on self-managed),
      # so we need to introduce another input for it.
      # We probably need to split up `image_registry_base` and use parts of it here, too.
      - project: 'components/opentofu'
        file: '/templates/validate-plan-apply.yml'
        ref: '$[[ inputs.version ]]'
        inputs:
          stage_validate: $[[ inputs.stage_validate ]]
          stage_build: $[[ inputs.stage_build ]]
          stage_deploy: $[[ inputs.stage_deploy ]]
          version: $[[ inputs.version ]]
          base_os: $[[ inputs.base_os ]]
          opentofu_version: $[[ inputs.opentofu_version ]]
          image_registry_base: $[[ inputs.image_registry_base ]]
          image_name: $[[ inputs.image_name]]
          image_digest: $[[ inputs.image_digest]]
          job_name_prefix: $[[ inputs.job_name_prefix]]
          root_dir: $[[ inputs.root_dir]]
          state_name: $[[ inputs.state_name]]
          plan_name: $[[ inputs.plan_name ]]
          plan_artifacts_access: $[[ inputs.plan_artifacts_access ]]
          plan_extra_artifacts: $[[ inputs.plan_extra_artifacts ]]
          var_file: $[[ inputs.var_file ]]
          fmt_rules: $[[ inputs.fmt_rules ]]
          fmt_allow_failure: $[[ inputs.fmt_allow_failure ]]
          validate_rules: $[[ inputs.validate_rules ]]
          plan_rules: $[[ inputs.plan_rules ]]
          apply_rules: $[[ inputs.apply_rules ]]
          warning_on_non_empty_plan: $[[ inputs.warning_on_non_empty_plan ]]
          auto_encryption: $[[ inputs.auto_encryption ]]
          auto_encryption_passphrase: $[[ inputs.auto_encryption_passphrase ]]
          auto_encryption_enable_migration_from_unencrypted: $[[ inputs.auto_encryption_enable_migration_from_unencrypted ]]
          allow_developer_role_to_plan: $[[ inputs.allow_developer_role_to_plan ]]
          auto_define_backend: $[[ inputs.auto_define_backend ]]
          enable_id_tokens: $[[ inputs.enable_id_tokens ]]
          id_tokens_base_job_name: $[[ inputs.id_tokens_base_job_name ]]
          id_tokens_setup_script: $[[ inputs.id_tokens_setup_script ]]
          use_mr_plan: $[[ inputs.use_mr_plan ]]
          drift_detection_mode: $[[ inputs.drift_detection_mode ]]
          post_mr_plan_comment: $[[ inputs.post_mr_plan_comment ]]
          trigger_in_child_pipeline: false
    forward:
      yaml_variables: true
      pipeline_variables: true
    strategy: depend
